version: '3.1'
assistant_id: 20240712-optimized-chatbot
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: CountVectorsFeaturizer
  analyzer: word
  min_ngram: 1
  max_ngram: 2
- name: DIETClassifier
  epochs: 20
  constrain_similarities: true
  model_confidence: softmax
  batch_size:
  - 64
  - 256
  eval_num_examples: 20
  eval_num_epochs: 4
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 20
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1
policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 2
  epochs: 20
- name: TEDPolicy
  max_history: 2
  epochs: 20
  constrain_similarities: true
